import type { NextPage } from "next";
import Head from "next/head";

import "twin.macro";

import * as S from "../styles/home.styles";

const Home: NextPage = () => {
  return (
    <S.Container>
      <Head>
        <title>Yuk Pulih</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <S.AboutUs />

    </S.Container>
  );
};

export default Home;
