import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navigation/navbar/navbar.component";

const menuProps = [
  {
    name: "Workshop",
    url: "#",
    subMenu: [
      {
        name: "Category 1",
        url: "#",
        subSubMenu: [
          { name: "Sub Sub-menu 1", url: "#" },
          { name: "Sub Sub-menu 2", url: "#" },
        ],
      },
    ],
  },
  {
    name: "About",
    url: "#",
    subMenu: [
      {
        name: "Sub Menu 1",
        url: "#",
        subSubMenu: null,
      },
      {
        name: "Sub Menu 2",
        url: "#",
        subSubMenu: null,
      },
    ],
  },
  {
    name: "Blog",
    url: "#",
    subMenu: null,
  },
  {
    name: "Community",
    url: "#",
    subMenu: null,
  },
  {
    name: "Donate",
    url: "#",
    subMenu: null,
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Yuk Pulih</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar menu={menuProps} />
    </div>
  );
};

export default Home;
